INSERT INTO customer (name, phone_number, email, city, zip_code, address) VALUES ('Nagy Tibor', '+36305584221', 'tibor.nagy@fakemail.com', 'Budapest', 1023, 'Akácfa utca 17.');
INSERT INTO customer (name, phone_number, email, city, zip_code, address) VALUES ('Horváth Katalin', '+36703483345', 'katalin.horvath@fakemail.com', 'Szeged', 6727, 'Fecske utca 4.');
INSERT INTO customer (name, phone_number, email, city, zip_code, address) VALUES ('Simon Ferenc', '+36302547546', 'ferenc.simon@fakemail.com', 'Székesfehérvár', 8000, 'Balfi út 34.');
INSERT INTO customer (name, phone_number, email, city, zip_code, address) VALUES ('Kiss Ádám', '+36207747785', 'adam.kiss@fakemail.com', 'Sopron', 9400, 'Szent Vendel utca 26.');


INSERT INTO parcel (customer_id, recipient_name, recipient_phone_number, recipient_email, recipient_city, recipient_zip_code, recipient_address, cash_on_delivery, parcel_size, status) VALUES (2, 'Tóth István', '+36305478332', 'istvan.toth@fakemail.com', 'Budapest', 1014, 'Tószegi út 112.', 0, 'S', 'DELIVERED');
INSERT INTO parcel (customer_id, recipient_name, recipient_phone_number, recipient_email, recipient_city, recipient_zip_code, recipient_address, cash_on_delivery, parcel_size, status) VALUES (3, 'Gáspár Tamás', '+36309663254', 'tamas.gaspar@fakemail.com', 'Szolnok', 5000, 'Kocsis köz 3.', 0, 'L', 'UNDELIVERED');
INSERT INTO parcel (customer_id, recipient_name, recipient_phone_number, recipient_email, recipient_city, recipient_zip_code, recipient_address, cash_on_delivery, parcel_size, status) VALUES (3, 'Somogyi Nóra', '+36707875521', 'nora.somogyi@fakemail.com', 'Siófok', 8600, 'Forrás tér 2.', 14000, 'M', 'DELIVERED');
INSERT INTO parcel (customer_id, recipient_name, recipient_phone_number, recipient_email, recipient_city, recipient_zip_code, recipient_address, cash_on_delivery, parcel_size, status) VALUES (4, 'Lukács Dávid', '+36305597852', 'david.lukacs@fakemail.com', 'Budapest', 1034, 'Mester utca 18.', 3990, 'S', 'DELIVERED');
INSERT INTO parcel (customer_id, recipient_name, recipient_phone_number, recipient_email, recipient_city, recipient_zip_code, recipient_address, cash_on_delivery, parcel_size, status) VALUES (4, 'Soós Péter', '+36207113657', 'peter.soos@fakemail.com', 'Szentendre', 2000, 'Ady Endre út 46.', 0, 'M', 'IN_TRANSIT');
INSERT INTO parcel (customer_id, recipient_name, recipient_phone_number, recipient_email, recipient_city, recipient_zip_code, recipient_address, cash_on_delivery, parcel_size, status) VALUES (4, 'Németh Réka', '+36303475447', 'reka.nemeth@fakemail.com', 'Eger', 3300, 'Hársfa utca 11.', 49990, 'XL', 'NEW');