create table customer (
    id bigint generated by default as identity,
    name varchar(255),
    phone_number varchar(255),
    email varchar(255),
    city varchar(255),
    zip_code integer,
    address varchar(255),
    primary key (id)
);