create table parcel (
    id bigint generated by default as identity,
    customer_id bigint,
    recipient_name varchar(255),
    recipient_phone_number varchar(255),
    recipient_email varchar(255),
    recipient_city varchar(255),
    recipient_zip_code integer,
    recipient_address varchar(255),
    cash_on_delivery integer,
    parcel_size varchar(255),
    status varchar(255),
    primary key (id)
);

alter table parcel add constraint FK_ParcelCustomer foreign key (customer_id) references customer;